### ISSUE TITLE
Spotlight should only be occupied by one person only

### ISSUE THREAD

**Issue by sk8eddie** [konglobemeralt/1337xXSlayer#5]
Right now many players can enter the spotlight control board and this should not be the case. Will probably solve this by using different states.

**Comment by konglobemeralt** [comment]
Might be considered a feature as this allows the saboteur to potentially cause confusion when another player uses the spotlight. There is  also the possibility that it can cause confusion if the supervisors are uncoordinated and simply try to use it at the same time.

**Comment by konglobemeralt** [comment]
Group agrees that this is fun.
